apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "synqx.fullname" . }}-frontend
  labels:
    {{- include "synqx.labels" . | nindent 4 }}
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "synqx.selectorLabels" . | nindent 6 }}
      component: frontend
  template:
    metadata:
      labels:
        {{- include "synqx.selectorLabels" . | nindent 8 }}
        component: frontend
    spec:
      serviceAccountName: {{ include "synqx.serviceAccountName" . }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "synqx.fullname" . }}-frontend
  labels:
    {{- include "synqx.labels" . | nindent 4 }}
    component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "synqx.selectorLabels" . | nindent 4 }}
    component: frontend
