apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synqx.fullname" . }}-secrets
  labels:
    {{- include "synqx.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  redis-password: {{ .Values.redis.auth.password | default "" | b64enc | quote }}
  secret-key: {{ .Values.secrets.secretKey | b64enc | quote }}
  master-password: {{ .Values.secrets.masterPassword | b64enc | quote }}
